apiVersion: v2
name: "<name>"
description: Helm chart for the YTsaurus Kubernetes operator that deploys and manages YTsaurus clusters
type: application
version: "<version>"
appVersion: "<version>"
sources:
  - https://github.com/ytsaurus/ytsaurus-k8s-operator
