apiVersion: v2
name: "ytop-chart"
description: Helm chart for the YTsaurus Kubernetes operator that deploys and manages YTsaurus clusters
type: application
version: "0.0.0-devel"
appVersion: "0.0.0-devel"
kubeVersion: ">=1.29.0"
sources:
  - https://github.com/ytsaurus/ytsaurus-k8s-operator
