//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseLoggerSpec) DeepCopyInto(out *BaseLoggerSpec) {
	*out = *in
	if in.RotationPolicy != nil {
		in, out := &in.RotationPolicy, &out.RotationPolicy
		*out = new(LogRotationPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseLoggerSpec.
func (in *BaseLoggerSpec) DeepCopy() *BaseLoggerSpec {
	if in == nil {
		return nil
	}
	out := new(BaseLoggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	if in.TabletCellBundles != nil {
		in, out := &in.TabletCellBundles, &out.TabletCellBundles
		*out = new(BundlesBootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleBootstrapSpec) DeepCopyInto(out *BundleBootstrapSpec) {
	*out = *in
	if in.SnapshotPrimaryMedium != nil {
		in, out := &in.SnapshotPrimaryMedium, &out.SnapshotPrimaryMedium
		*out = new(string)
		**out = **in
	}
	if in.ChangelogPrimaryMedium != nil {
		in, out := &in.ChangelogPrimaryMedium, &out.ChangelogPrimaryMedium
		*out = new(string)
		**out = **in
	}
	if in.NodeTagFilter != nil {
		in, out := &in.NodeTagFilter, &out.NodeTagFilter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleBootstrapSpec.
func (in *BundleBootstrapSpec) DeepCopy() *BundleBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BundleBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundlesBootstrapSpec) DeepCopyInto(out *BundlesBootstrapSpec) {
	*out = *in
	if in.Sys != nil {
		in, out := &in.Sys, &out.Sys
		*out = new(BundleBootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(BundleBootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundlesBootstrapSpec.
func (in *BundlesBootstrapSpec) DeepCopy() *BundlesBootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BundlesBootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRIJobEnvironmentSpec) DeepCopyInto(out *CRIJobEnvironmentSpec) {
	*out = *in
	if in.EntrypointWrapper != nil {
		in, out := &in.EntrypointWrapper, &out.EntrypointWrapper
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SandboxImage != nil {
		in, out := &in.SandboxImage, &out.SandboxImage
		*out = new(string)
		**out = **in
	}
	if in.APIRetryTimeoutSeconds != nil {
		in, out := &in.APIRetryTimeoutSeconds, &out.APIRetryTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CRINamespace != nil {
		in, out := &in.CRINamespace, &out.CRINamespace
		*out = new(string)
		**out = **in
	}
	if in.BaseCgroup != nil {
		in, out := &in.BaseCgroup, &out.BaseCgroup
		*out = new(string)
		**out = **in
	}
	if in.RegistryConfigPath != nil {
		in, out := &in.RegistryConfigPath, &out.RegistryConfigPath
		*out = new(string)
		**out = **in
	}
	if in.ImageSizeEstimation != nil {
		in, out := &in.ImageSizeEstimation, &out.ImageSizeEstimation
		*out = new(int64)
		**out = **in
	}
	if in.ImageCompressionRatioEstimation != nil {
		in, out := &in.ImageCompressionRatioEstimation, &out.ImageCompressionRatioEstimation
		*out = new(int32)
		**out = **in
	}
	if in.AlwaysPullLatestImage != nil {
		in, out := &in.AlwaysPullLatestImage, &out.AlwaysPullLatestImage
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullPeriodSeconds != nil {
		in, out := &in.ImagePullPeriodSeconds, &out.ImagePullPeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRIJobEnvironmentSpec.
func (in *CRIJobEnvironmentSpec) DeepCopy() *CRIJobEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(CRIJobEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoriesFilter) DeepCopyInto(out *CategoriesFilter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoriesFilter.
func (in *CategoriesFilter) DeepCopy() *CategoriesFilter {
	if in == nil {
		return nil
	}
	out := new(CategoriesFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Chyt) DeepCopyInto(out *Chyt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chyt.
func (in *Chyt) DeepCopy() *Chyt {
	if in == nil {
		return nil
	}
	out := new(Chyt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Chyt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChytList) DeepCopyInto(out *ChytList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Chyt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChytList.
func (in *ChytList) DeepCopy() *ChytList {
	if in == nil {
		return nil
	}
	out := new(ChytList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChytList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChytSpec) DeepCopyInto(out *ChytSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Ytsaurus != nil {
		in, out := &in.Ytsaurus, &out.Ytsaurus
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.CreatePublicClique != nil {
		in, out := &in.CreatePublicClique, &out.CreatePublicClique
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChytSpec.
func (in *ChytSpec) DeepCopy() *ChytSpec {
	if in == nil {
		return nil
	}
	out := new(ChytSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChytStatus) DeepCopyInto(out *ChytStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChytStatus.
func (in *ChytStatus) DeepCopy() *ChytStatus {
	if in == nil {
		return nil
	}
	out := new(ChytStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFeatures) DeepCopyInto(out *ClusterFeatures) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFeatures.
func (in *ClusterFeatures) DeepCopy() *ClusterFeatures {
	if in == nil {
		return nil
	}
	out := new(ClusterFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNodesSpec) DeepCopyInto(out *ClusterNodesSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNodesSpec.
func (in *ClusterNodesSpec) DeepCopy() *ClusterNodesSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonRemoteNodeStatus) DeepCopyInto(out *CommonRemoteNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonRemoteNodeStatus.
func (in *CommonRemoteNodeStatus) DeepCopy() *CommonRemoteNodeStatus {
	if in == nil {
		return nil
	}
	out := new(CommonRemoteNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonSpec) DeepCopyInto(out *CommonSpec) {
	*out = *in
	if in.ClusterFeatures != nil {
		in, out := &in.ClusterFeatures, &out.ClusterFeatures
		*out = new(ClusterFeatures)
		**out = **in
	}
	if in.JobImage != nil {
		in, out := &in.JobImage, &out.JobImage
		*out = new(string)
		**out = **in
	}
	if in.CABundle != nil {
		in, out := &in.CABundle, &out.CABundle
		*out = new(FileObjectReference)
		**out = **in
	}
	if in.NativeTransport != nil {
		in, out := &in.NativeTransport, &out.NativeTransport
		*out = new(RPCTransportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KeepSocket != nil {
		in, out := &in.KeepSocket, &out.KeepSocket
		*out = new(bool)
		**out = **in
	}
	if in.ForceTCP != nil {
		in, out := &in.ForceTCP, &out.ForceTCP
		*out = new(bool)
		**out = **in
	}
	if in.ExtraPodAnnotations != nil {
		in, out := &in.ExtraPodAnnotations, &out.ExtraPodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigOverrides != nil {
		in, out := &in.ConfigOverrides, &out.ConfigOverrides
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonSpec.
func (in *CommonSpec) DeepCopy() *CommonSpec {
	if in == nil {
		return nil
	}
	out := new(CommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Component) DeepCopyInto(out *Component) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Component.
func (in *Component) DeepCopy() *Component {
	if in == nil {
		return nil
	}
	out := new(Component)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentUpdateSelector) DeepCopyInto(out *ComponentUpdateSelector) {
	*out = *in
	out.Component = in.Component
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentUpdateSelector.
func (in *ComponentUpdateSelector) DeepCopy() *ComponentUpdateSelector {
	if in == nil {
		return nil
	}
	out := new(ComponentUpdateSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerAgentsSpec) DeepCopyInto(out *ControllerAgentsSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerAgentsSpec.
func (in *ControllerAgentsSpec) DeepCopy() *ControllerAgentsSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerAgentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNodesSpec) DeepCopyInto(out *DataNodesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	in.ClusterNodesSpec.DeepCopyInto(&out.ClusterNodesSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNodesSpec.
func (in *DataNodesSpec) DeepCopy() *DataNodesSpec {
	if in == nil {
		return nil
	}
	out := new(DataNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeprecatedSpytSpec) DeepCopyInto(out *DeprecatedSpytSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeprecatedSpytSpec.
func (in *DeprecatedSpytSpec) DeepCopy() *DeprecatedSpytSpec {
	if in == nil {
		return nil
	}
	out := new(DeprecatedSpytSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverySpec) DeepCopyInto(out *DiscoverySpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverySpec.
func (in *DiscoverySpec) DeepCopy() *DiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(DiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedObjectMetadata) DeepCopyInto(out *EmbeddedObjectMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedObjectMetadata.
func (in *EmbeddedObjectMetadata) DeepCopy() *EmbeddedObjectMetadata {
	if in == nil {
		return nil
	}
	out := new(EmbeddedObjectMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedPersistentVolumeClaim) DeepCopyInto(out *EmbeddedPersistentVolumeClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.EmbeddedObjectMetadata.DeepCopyInto(&out.EmbeddedObjectMetadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedPersistentVolumeClaim.
func (in *EmbeddedPersistentVolumeClaim) DeepCopy() *EmbeddedPersistentVolumeClaim {
	if in == nil {
		return nil
	}
	out := new(EmbeddedPersistentVolumeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecNodesSpec) DeepCopyInto(out *ExecNodesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	in.ClusterNodesSpec.DeepCopyInto(&out.ClusterNodesSpec)
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JobProxyLoggers != nil {
		in, out := &in.JobProxyLoggers, &out.JobProxyLoggers
		*out = make([]TextLoggerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JobResources != nil {
		in, out := &in.JobResources, &out.JobResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.JobEnvironment != nil {
		in, out := &in.JobEnvironment, &out.JobEnvironment
		*out = new(JobEnvironmentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecNodesSpec.
func (in *ExecNodesSpec) DeepCopy() *ExecNodesSpec {
	if in == nil {
		return nil
	}
	out := new(ExecNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileObjectReference) DeepCopyInto(out *FileObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileObjectReference.
func (in *FileObjectReference) DeepCopy() *FileObjectReference {
	if in == nil {
		return nil
	}
	out := new(FileObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxiesSpec) DeepCopyInto(out *HTTPProxiesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	if in.HttpPort != nil {
		in, out := &in.HttpPort, &out.HttpPort
		*out = new(int32)
		**out = **in
	}
	if in.HttpsPort != nil {
		in, out := &in.HttpsPort, &out.HttpsPort
		*out = new(int32)
		**out = **in
	}
	if in.HttpNodePort != nil {
		in, out := &in.HttpNodePort, &out.HttpNodePort
		*out = new(int32)
		**out = **in
	}
	if in.HttpsNodePort != nil {
		in, out := &in.HttpsNodePort, &out.HttpsNodePort
		*out = new(int32)
		**out = **in
	}
	in.Transport.DeepCopyInto(&out.Transport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxiesSpec.
func (in *HTTPProxiesSpec) DeepCopy() *HTTPProxiesSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPProxiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPTransportSpec) DeepCopyInto(out *HTTPTransportSpec) {
	*out = *in
	if in.HTTPSSecret != nil {
		in, out := &in.HTTPSSecret, &out.HTTPSSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPTransportSpec.
func (in *HTTPTransportSpec) DeepCopy() *HTTPTransportSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPTransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckProbeParams) DeepCopyInto(out *HealthcheckProbeParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckProbeParams.
func (in *HealthcheckProbeParams) DeepCopy() *HealthcheckProbeParams {
	if in == nil {
		return nil
	}
	out := new(HealthcheckProbeParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HydraPersistenceUploaderSpec) DeepCopyInto(out *HydraPersistenceUploaderSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HydraPersistenceUploaderSpec.
func (in *HydraPersistenceUploaderSpec) DeepCopy() *HydraPersistenceUploaderSpec {
	if in == nil {
		return nil
	}
	out := new(HydraPersistenceUploaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.EntrypointWrapper != nil {
		in, out := &in.EntrypointWrapper, &out.EntrypointWrapper
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadinessProbeParams != nil {
		in, out := &in.ReadinessProbeParams, &out.ReadinessProbeParams
		*out = new(HealthcheckProbeParams)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.MinReadyInstanceCount != nil {
		in, out := &in.MinReadyInstanceCount, &out.MinReadyInstanceCount
		*out = new(int)
		**out = **in
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]LocationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]EmbeddedPersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.EnableAntiAffinity != nil {
		in, out := &in.EnableAntiAffinity, &out.EnableAntiAffinity
		*out = new(bool)
		**out = **in
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	if in.MonitoringPort != nil {
		in, out := &in.MonitoringPort, &out.MonitoringPort
		*out = new(int32)
		**out = **in
	}
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make([]TextLoggerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StructuredLoggers != nil {
		in, out := &in.StructuredLoggers, &out.StructuredLoggers
		*out = make([]StructuredLoggerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SetHostnameAsFQDN != nil {
		in, out := &in.SetHostnameAsFQDN, &out.SetHostnameAsFQDN
		*out = new(bool)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NativeTransport != nil {
		in, out := &in.NativeTransport, &out.NativeTransport
		*out = new(RPCTransportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(corev1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobEnvironmentSpec) DeepCopyInto(out *JobEnvironmentSpec) {
	*out = *in
	if in.Isolated != nil {
		in, out := &in.Isolated, &out.Isolated
		*out = new(bool)
		**out = **in
	}
	if in.UserSlots != nil {
		in, out := &in.UserSlots, &out.UserSlots
		*out = new(int)
		**out = **in
	}
	if in.CRI != nil {
		in, out := &in.CRI, &out.CRI
		*out = new(CRIJobEnvironmentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.UseArtifactBinds != nil {
		in, out := &in.UseArtifactBinds, &out.UseArtifactBinds
		*out = new(bool)
		**out = **in
	}
	if in.DoNotSetUserId != nil {
		in, out := &in.DoNotSetUserId, &out.DoNotSetUserId
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobEnvironmentSpec.
func (in *JobEnvironmentSpec) DeepCopy() *JobEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(JobEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaProxiesSpec) DeepCopyInto(out *KafkaProxiesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(corev1.ServiceType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaProxiesSpec.
func (in *KafkaProxiesSpec) DeepCopy() *KafkaProxiesSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaProxiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationSpec) DeepCopyInto(out *LocationSpec) {
	*out = *in
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.LowWatermark != nil {
		in, out := &in.LowWatermark, &out.LowWatermark
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTrashMilliseconds != nil {
		in, out := &in.MaxTrashMilliseconds, &out.MaxTrashMilliseconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationSpec.
func (in *LocationSpec) DeepCopy() *LocationSpec {
	if in == nil {
		return nil
	}
	out := new(LocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRotationPolicy) DeepCopyInto(out *LogRotationPolicy) {
	*out = *in
	if in.RotationPeriodMilliseconds != nil {
		in, out := &in.RotationPeriodMilliseconds, &out.RotationPeriodMilliseconds
		*out = new(int64)
		**out = **in
	}
	if in.MaxSegmentSize != nil {
		in, out := &in.MaxSegmentSize, &out.MaxSegmentSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxTotalSizeToKeep != nil {
		in, out := &in.MaxTotalSizeToKeep, &out.MaxTotalSizeToKeep
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxSegmentCountToKeep != nil {
		in, out := &in.MaxSegmentCountToKeep, &out.MaxSegmentCountToKeep
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRotationPolicy.
func (in *LogRotationPolicy) DeepCopy() *LogRotationPolicy {
	if in == nil {
		return nil
	}
	out := new(LogRotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterCachesConnectionSpec) DeepCopyInto(out *MasterCachesConnectionSpec) {
	*out = *in
	if in.HostAddresses != nil {
		in, out := &in.HostAddresses, &out.HostAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterCachesConnectionSpec.
func (in *MasterCachesConnectionSpec) DeepCopy() *MasterCachesConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MasterCachesConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterCachesSpec) DeepCopyInto(out *MasterCachesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	in.MasterCachesConnectionSpec.DeepCopyInto(&out.MasterCachesConnectionSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterCachesSpec.
func (in *MasterCachesSpec) DeepCopy() *MasterCachesSpec {
	if in == nil {
		return nil
	}
	out := new(MasterCachesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterConnectionSpec) DeepCopyInto(out *MasterConnectionSpec) {
	*out = *in
	if in.HostAddresses != nil {
		in, out := &in.HostAddresses, &out.HostAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterConnectionSpec.
func (in *MasterConnectionSpec) DeepCopy() *MasterConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MasterConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MastersSpec) DeepCopyInto(out *MastersSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	in.MasterConnectionSpec.DeepCopyInto(&out.MasterConnectionSpec)
	if in.MaxSnapshotCountToKeep != nil {
		in, out := &in.MaxSnapshotCountToKeep, &out.MaxSnapshotCountToKeep
		*out = new(int)
		**out = **in
	}
	if in.MaxChangelogCountToKeep != nil {
		in, out := &in.MaxChangelogCountToKeep, &out.MaxChangelogCountToKeep
		*out = new(int)
		**out = **in
	}
	if in.HydraPersistenceUploader != nil {
		in, out := &in.HydraPersistenceUploader, &out.HydraPersistenceUploader
		*out = new(HydraPersistenceUploaderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Timbertruck != nil {
		in, out := &in.Timbertruck, &out.Timbertruck
		*out = new(TimbertruckSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Sidecars != nil {
		in, out := &in.Sidecars, &out.Sidecars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MastersSpec.
func (in *MastersSpec) DeepCopy() *MastersSpec {
	if in == nil {
		return nil
	}
	out := new(MastersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthServiceSpec) DeepCopyInto(out *OauthServiceSpec) {
	*out = *in
	in.UserInfo.DeepCopyInto(&out.UserInfo)
	if in.DisableUserCreation != nil {
		in, out := &in.DisableUserCreation, &out.DisableUserCreation
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthServiceSpec.
func (in *OauthServiceSpec) DeepCopy() *OauthServiceSpec {
	if in == nil {
		return nil
	}
	out := new(OauthServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthUserInfoHandlerSpec) DeepCopyInto(out *OauthUserInfoHandlerSpec) {
	*out = *in
	if in.ErrorField != nil {
		in, out := &in.ErrorField, &out.ErrorField
		*out = new(string)
		**out = **in
	}
	if in.LoginTransformations != nil {
		in, out := &in.LoginTransformations, &out.LoginTransformations
		*out = make([]OauthUserLoginTransformation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthUserInfoHandlerSpec.
func (in *OauthUserInfoHandlerSpec) DeepCopy() *OauthUserInfoHandlerSpec {
	if in == nil {
		return nil
	}
	out := new(OauthUserInfoHandlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OauthUserLoginTransformation) DeepCopyInto(out *OauthUserLoginTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OauthUserLoginTransformation.
func (in *OauthUserLoginTransformation) DeepCopy() *OauthUserLoginTransformation {
	if in == nil {
		return nil
	}
	out := new(OauthUserLoginTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryTrackerSpec) DeepCopyInto(out *QueryTrackerSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryTrackerSpec.
func (in *QueryTrackerSpec) DeepCopy() *QueryTrackerSpec {
	if in == nil {
		return nil
	}
	out := new(QueryTrackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueAgentSpec) DeepCopyInto(out *QueueAgentSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueAgentSpec.
func (in *QueueAgentSpec) DeepCopy() *QueueAgentSpec {
	if in == nil {
		return nil
	}
	out := new(QueueAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPCProxiesSpec) DeepCopyInto(out *RPCProxiesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(corev1.ServiceType)
		**out = **in
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	in.Transport.DeepCopyInto(&out.Transport)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPCProxiesSpec.
func (in *RPCProxiesSpec) DeepCopy() *RPCProxiesSpec {
	if in == nil {
		return nil
	}
	out := new(RPCProxiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPCTransportSpec) DeepCopyInto(out *RPCTransportSpec) {
	*out = *in
	if in.TLSSecret != nil {
		in, out := &in.TLSSecret, &out.TLSSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.TLSClientSecret != nil {
		in, out := &in.TLSClientSecret, &out.TLSClientSecret
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPCTransportSpec.
func (in *RPCTransportSpec) DeepCopy() *RPCTransportSpec {
	if in == nil {
		return nil
	}
	out := new(RPCTransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteDataNodes) DeepCopyInto(out *RemoteDataNodes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteDataNodes.
func (in *RemoteDataNodes) DeepCopy() *RemoteDataNodes {
	if in == nil {
		return nil
	}
	out := new(RemoteDataNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteDataNodes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteDataNodesList) DeepCopyInto(out *RemoteDataNodesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteDataNodes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteDataNodesList.
func (in *RemoteDataNodesList) DeepCopy() *RemoteDataNodesList {
	if in == nil {
		return nil
	}
	out := new(RemoteDataNodesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteDataNodesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteDataNodesSpec) DeepCopyInto(out *RemoteDataNodesSpec) {
	*out = *in
	if in.RemoteClusterSpec != nil {
		in, out := &in.RemoteClusterSpec, &out.RemoteClusterSpec
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	in.DataNodesSpec.DeepCopyInto(&out.DataNodesSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteDataNodesSpec.
func (in *RemoteDataNodesSpec) DeepCopy() *RemoteDataNodesSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteDataNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteDataNodesStatus) DeepCopyInto(out *RemoteDataNodesStatus) {
	*out = *in
	out.CommonRemoteNodeStatus = in.CommonRemoteNodeStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteDataNodesStatus.
func (in *RemoteDataNodesStatus) DeepCopy() *RemoteDataNodesStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteDataNodesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteExecNodes) DeepCopyInto(out *RemoteExecNodes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteExecNodes.
func (in *RemoteExecNodes) DeepCopy() *RemoteExecNodes {
	if in == nil {
		return nil
	}
	out := new(RemoteExecNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteExecNodes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteExecNodesList) DeepCopyInto(out *RemoteExecNodesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteExecNodes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteExecNodesList.
func (in *RemoteExecNodesList) DeepCopy() *RemoteExecNodesList {
	if in == nil {
		return nil
	}
	out := new(RemoteExecNodesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteExecNodesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteExecNodesSpec) DeepCopyInto(out *RemoteExecNodesSpec) {
	*out = *in
	if in.RemoteClusterSpec != nil {
		in, out := &in.RemoteClusterSpec, &out.RemoteClusterSpec
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	in.ExecNodesSpec.DeepCopyInto(&out.ExecNodesSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteExecNodesSpec.
func (in *RemoteExecNodesSpec) DeepCopy() *RemoteExecNodesSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteExecNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteExecNodesStatus) DeepCopyInto(out *RemoteExecNodesStatus) {
	*out = *in
	out.CommonRemoteNodeStatus = in.CommonRemoteNodeStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteExecNodesStatus.
func (in *RemoteExecNodesStatus) DeepCopy() *RemoteExecNodesStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteExecNodesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteTabletNodes) DeepCopyInto(out *RemoteTabletNodes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteTabletNodes.
func (in *RemoteTabletNodes) DeepCopy() *RemoteTabletNodes {
	if in == nil {
		return nil
	}
	out := new(RemoteTabletNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteTabletNodes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteTabletNodesList) DeepCopyInto(out *RemoteTabletNodesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteTabletNodes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteTabletNodesList.
func (in *RemoteTabletNodesList) DeepCopy() *RemoteTabletNodesList {
	if in == nil {
		return nil
	}
	out := new(RemoteTabletNodesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteTabletNodesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteTabletNodesSpec) DeepCopyInto(out *RemoteTabletNodesSpec) {
	*out = *in
	if in.RemoteClusterSpec != nil {
		in, out := &in.RemoteClusterSpec, &out.RemoteClusterSpec
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	in.TabletNodesSpec.DeepCopyInto(&out.TabletNodesSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteTabletNodesSpec.
func (in *RemoteTabletNodesSpec) DeepCopy() *RemoteTabletNodesSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteTabletNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteTabletNodesStatus) DeepCopyInto(out *RemoteTabletNodesStatus) {
	*out = *in
	out.CommonRemoteNodeStatus = in.CommonRemoteNodeStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteTabletNodesStatus.
func (in *RemoteTabletNodesStatus) DeepCopy() *RemoteTabletNodesStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteTabletNodesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteYtsaurus) DeepCopyInto(out *RemoteYtsaurus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteYtsaurus.
func (in *RemoteYtsaurus) DeepCopy() *RemoteYtsaurus {
	if in == nil {
		return nil
	}
	out := new(RemoteYtsaurus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteYtsaurus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteYtsaurusList) DeepCopyInto(out *RemoteYtsaurusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteYtsaurus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteYtsaurusList.
func (in *RemoteYtsaurusList) DeepCopy() *RemoteYtsaurusList {
	if in == nil {
		return nil
	}
	out := new(RemoteYtsaurusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteYtsaurusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteYtsaurusSpec) DeepCopyInto(out *RemoteYtsaurusSpec) {
	*out = *in
	in.MasterConnectionSpec.DeepCopyInto(&out.MasterConnectionSpec)
	in.MasterCachesSpec.DeepCopyInto(&out.MasterCachesSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteYtsaurusSpec.
func (in *RemoteYtsaurusSpec) DeepCopy() *RemoteYtsaurusSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteYtsaurusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteYtsaurusStatus) DeepCopyInto(out *RemoteYtsaurusStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteYtsaurusStatus.
func (in *RemoteYtsaurusStatus) DeepCopy() *RemoteYtsaurusStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteYtsaurusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulersSpec) DeepCopyInto(out *SchedulersSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulersSpec.
func (in *SchedulersSpec) DeepCopy() *SchedulersSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spyt) DeepCopyInto(out *Spyt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spyt.
func (in *Spyt) DeepCopy() *Spyt {
	if in == nil {
		return nil
	}
	out := new(Spyt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Spyt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpytList) DeepCopyInto(out *SpytList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Spyt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpytList.
func (in *SpytList) DeepCopy() *SpytList {
	if in == nil {
		return nil
	}
	out := new(SpytList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpytList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpytSpec) DeepCopyInto(out *SpytSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Ytsaurus != nil {
		in, out := &in.Ytsaurus, &out.Ytsaurus
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpytSpec.
func (in *SpytSpec) DeepCopy() *SpytSpec {
	if in == nil {
		return nil
	}
	out := new(SpytSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpytStatus) DeepCopyInto(out *SpytStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpytStatus.
func (in *SpytStatus) DeepCopy() *SpytStatus {
	if in == nil {
		return nil
	}
	out := new(SpytStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrawberryControllerSpec) DeepCopyInto(out *StrawberryControllerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalProxy != nil {
		in, out := &in.ExternalProxy, &out.ExternalProxy
		*out = new(string)
		**out = **in
	}
	if in.ControllerFamilies != nil {
		in, out := &in.ControllerFamilies, &out.ControllerFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultRouteFamily != nil {
		in, out := &in.DefaultRouteFamily, &out.DefaultRouteFamily
		*out = new(string)
		**out = **in
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(corev1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrawberryControllerSpec.
func (in *StrawberryControllerSpec) DeepCopy() *StrawberryControllerSpec {
	if in == nil {
		return nil
	}
	out := new(StrawberryControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructuredLoggerSpec) DeepCopyInto(out *StructuredLoggerSpec) {
	*out = *in
	in.BaseLoggerSpec.DeepCopyInto(&out.BaseLoggerSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructuredLoggerSpec.
func (in *StructuredLoggerSpec) DeepCopy() *StructuredLoggerSpec {
	if in == nil {
		return nil
	}
	out := new(StructuredLoggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPProxiesSpec) DeepCopyInto(out *TCPProxiesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	if in.ServiceType != nil {
		in, out := &in.ServiceType, &out.ServiceType
		*out = new(corev1.ServiceType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPProxiesSpec.
func (in *TCPProxiesSpec) DeepCopy() *TCPProxiesSpec {
	if in == nil {
		return nil
	}
	out := new(TCPProxiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletCellBundleInfo) DeepCopyInto(out *TabletCellBundleInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletCellBundleInfo.
func (in *TabletCellBundleInfo) DeepCopy() *TabletCellBundleInfo {
	if in == nil {
		return nil
	}
	out := new(TabletCellBundleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletNodesSpec) DeepCopyInto(out *TabletNodesSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
	in.ClusterNodesSpec.DeepCopyInto(&out.ClusterNodesSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletNodesSpec.
func (in *TabletNodesSpec) DeepCopy() *TabletNodesSpec {
	if in == nil {
		return nil
	}
	out := new(TabletNodesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextLoggerSpec) DeepCopyInto(out *TextLoggerSpec) {
	*out = *in
	in.BaseLoggerSpec.DeepCopyInto(&out.BaseLoggerSpec)
	if in.CategoriesFilter != nil {
		in, out := &in.CategoriesFilter, &out.CategoriesFilter
		*out = new(CategoriesFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextLoggerSpec.
func (in *TextLoggerSpec) DeepCopy() *TextLoggerSpec {
	if in == nil {
		return nil
	}
	out := new(TextLoggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimbertruckSpec) DeepCopyInto(out *TimbertruckSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.DirectoryPath != nil {
		in, out := &in.DirectoryPath, &out.DirectoryPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimbertruckSpec.
func (in *TimbertruckSpec) DeepCopy() *TimbertruckSpec {
	if in == nil {
		return nil
	}
	out := new(TimbertruckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UISpec) DeepCopyInto(out *UISpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.HttpNodePort != nil {
		in, out := &in.HttpNodePort, &out.HttpNodePort
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ExternalProxy != nil {
		in, out := &in.ExternalProxy, &out.ExternalProxy
		*out = new(string)
		**out = **in
	}
	if in.OdinBaseUrl != nil {
		in, out := &in.OdinBaseUrl, &out.OdinBaseUrl
		*out = new(string)
		**out = **in
	}
	if in.ExtraEnvVariables != nil {
		in, out := &in.ExtraEnvVariables, &out.ExtraEnvVariables
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.DirectDownload != nil {
		in, out := &in.DirectDownload, &out.DirectDownload
		*out = new(bool)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(corev1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UISpec.
func (in *UISpec) DeepCopy() *UISpec {
	if in == nil {
		return nil
	}
	out := new(UISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStatus) DeepCopyInto(out *UpdateStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpdatingComponents != nil {
		in, out := &in.UpdatingComponents, &out.UpdatingComponents
		*out = make([]Component, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TabletCellBundles != nil {
		in, out := &in.TabletCellBundles, &out.TabletCellBundles
		*out = make([]TabletCellBundleInfo, len(*in))
		copy(*out, *in)
	}
	if in.MasterMonitoringPaths != nil {
		in, out := &in.MasterMonitoringPaths, &out.MasterMonitoringPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStatus.
func (in *UpdateStatus) DeepCopy() *UpdateStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YQLAgentSpec) DeepCopyInto(out *YQLAgentSpec) {
	*out = *in
	in.InstanceSpec.DeepCopyInto(&out.InstanceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YQLAgentSpec.
func (in *YQLAgentSpec) DeepCopy() *YQLAgentSpec {
	if in == nil {
		return nil
	}
	out := new(YQLAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ytsaurus) DeepCopyInto(out *Ytsaurus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ytsaurus.
func (in *Ytsaurus) DeepCopy() *Ytsaurus {
	if in == nil {
		return nil
	}
	out := new(Ytsaurus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ytsaurus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YtsaurusList) DeepCopyInto(out *YtsaurusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ytsaurus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YtsaurusList.
func (in *YtsaurusList) DeepCopy() *YtsaurusList {
	if in == nil {
		return nil
	}
	out := new(YtsaurusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YtsaurusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YtsaurusSpec) DeepCopyInto(out *YtsaurusSpec) {
	*out = *in
	in.CommonSpec.DeepCopyInto(&out.CommonSpec)
	if in.AdminCredentials != nil {
		in, out := &in.AdminCredentials, &out.AdminCredentials
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.OauthService != nil {
		in, out := &in.OauthService, &out.OauthService
		*out = new(OauthServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdatePlan != nil {
		in, out := &in.UpdatePlan, &out.UpdatePlan
		*out = make([]ComponentUpdateSelector, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(corev1.PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(BootstrapSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Discovery.DeepCopyInto(&out.Discovery)
	in.PrimaryMasters.DeepCopyInto(&out.PrimaryMasters)
	if in.SecondaryMasters != nil {
		in, out := &in.SecondaryMasters, &out.SecondaryMasters
		*out = make([]MastersSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MasterCaches != nil {
		in, out := &in.MasterCaches, &out.MasterCaches
		*out = new(MasterCachesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPProxies != nil {
		in, out := &in.HTTPProxies, &out.HTTPProxies
		*out = make([]HTTPProxiesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RPCProxies != nil {
		in, out := &in.RPCProxies, &out.RPCProxies
		*out = make([]RPCProxiesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TCPProxies != nil {
		in, out := &in.TCPProxies, &out.TCPProxies
		*out = make([]TCPProxiesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KafkaProxies != nil {
		in, out := &in.KafkaProxies, &out.KafkaProxies
		*out = make([]KafkaProxiesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataNodes != nil {
		in, out := &in.DataNodes, &out.DataNodes
		*out = make([]DataNodesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExecNodes != nil {
		in, out := &in.ExecNodes, &out.ExecNodes
		*out = make([]ExecNodesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedulers != nil {
		in, out := &in.Schedulers, &out.Schedulers
		*out = new(SchedulersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ControllerAgents != nil {
		in, out := &in.ControllerAgents, &out.ControllerAgents
		*out = new(ControllerAgentsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TabletNodes != nil {
		in, out := &in.TabletNodes, &out.TabletNodes
		*out = make([]TabletNodesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StrawberryController != nil {
		in, out := &in.StrawberryController, &out.StrawberryController
		*out = new(StrawberryControllerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryTrackers != nil {
		in, out := &in.QueryTrackers, &out.QueryTrackers
		*out = new(QueryTrackerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Spyt != nil {
		in, out := &in.Spyt, &out.Spyt
		*out = new(DeprecatedSpytSpec)
		**out = **in
	}
	if in.YQLAgents != nil {
		in, out := &in.YQLAgents, &out.YQLAgents
		*out = new(YQLAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.QueueAgents != nil {
		in, out := &in.QueueAgents, &out.QueueAgents
		*out = new(QueueAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YtsaurusSpec.
func (in *YtsaurusSpec) DeepCopy() *YtsaurusSpec {
	if in == nil {
		return nil
	}
	out := new(YtsaurusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YtsaurusStatus) DeepCopyInto(out *YtsaurusStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.UpdateStatus.DeepCopyInto(&out.UpdateStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YtsaurusStatus.
func (in *YtsaurusStatus) DeepCopy() *YtsaurusStatus {
	if in == nil {
		return nil
	}
	out := new(YtsaurusStatus)
	in.DeepCopyInto(out)
	return out
}
