# yaml-language-server: $schema=https://raw.githubusercontent.com/ytsaurus/ytsaurus-k8s-operator/refs/heads/main/config/crd/schema/cluster.ytsaurus.tech_chyt_v1.json

apiVersion: cluster.ytsaurus.tech/v1
kind: Chyt
metadata:
  name: mychyt
spec:
  ytsaurus:
    name:
      minisaurus
  # https://ytsaurus.tech/docs/en/admin-guide/releases#chyt
  # append "-relwithdebinfo" for image with debug symbols
  image: ghcr.io/ytsaurus/chyt:2.18.3
  makeDefault: true
  createPublicClique: true
