package components

import (
	"context"
	"fmt"
	"path"
	"strings"

	"k8s.io/utils/ptr"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	ytv1 "github.com/ytsaurus/ytsaurus-k8s-operator/api/v1"

	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/apiproxy"
	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/consts"
	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/labeller"
	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/resources"
)

const initJobPrologue = `#!/bin/bash
# YTsaurus init job script generated by ytsaurus-k8s-operator

set -eux -o pipefail
`

func initJobWithNativeDriverPrologue() string {
	commands := []string{
		initJobPrologue,
		fmt.Sprintf("export YT_DRIVER_CONFIG_PATH=%s", path.Join(consts.ConfigMountPoint, consts.ClientConfigFileName)),
		`export YTSAURUS_VERSION="$(/usr/bin/ytserver-all --version | head -c4)"`,
	}
	return strings.Join(commands, "\n")
}

type InitJob struct {
	component

	commonSpec    *ytv1.CommonSpec
	commonPodSpec *ytv1.PodSpec
	instanceSpec  *ytv1.InstanceSpec

	initJob *resources.Job
	configs *ConfigMapBuilder
	script  TextGeneratorFunc
	envFrom []corev1.EnvFromSource

	caRootBundle    *resources.CABundle
	caBundle        *resources.CABundle
	busClientSecret *resources.TLSSecret

	statusCondition string // Condition for tracking job state.
	reason          string // Changing reason triggers fresh start.

	builtJob *batchv1.Job
}

func NewInitJob(
	labeller *labeller.Labeller,
	apiProxy apiproxy.APIProxy,
	name string,
	configFileName string,
	generator ConfigGeneratorFunc,
	commonSpec *ytv1.CommonSpec,
	commonPodSpec *ytv1.PodSpec,
	instanceSpec *ytv1.InstanceSpec,
) *InitJob {
	var busClientSecret *resources.TLSSecret

	if transportSpec := commonSpec.NativeTransport; transportSpec != nil {
		if transportSpec.TLSClientSecret != nil {
			busClientSecret = resources.NewTLSSecret(
				transportSpec.TLSClientSecret.Name,
				consts.BusClientSecretVolumeName,
				consts.BusClientSecretMountPoint)
		}
	}

	initJob := &InitJob{
		component: component{
			labeller: labeller,
			owner:    apiProxy,
		},
		commonSpec:      commonSpec,
		commonPodSpec:   commonPodSpec,
		instanceSpec:    instanceSpec,
		statusCondition: labeller.GetInitJobCompletedCondition(name),
		reason:          "InitJob",
		initJob: resources.NewJob(
			labeller.GetInitJobName(name),
			labeller,
			apiProxy,
		),
		caRootBundle:    resources.NewCARootBundle(commonSpec.CARootBundle),
		caBundle:        resources.NewCABundle(commonSpec.CABundle),
		busClientSecret: busClientSecret,
		configs:         NewConfigMapBuilder(labeller, apiProxy, labeller.GetInitJobConfigMapName(name), nil),
		script: func() ([]string, error) {
			return nil, fmt.Errorf("script undefined")
		},
	}

	initJob.configs.AddGenerator(configFileName, ConfigFormatYson, generator)
	initJob.configs.AddGenerator(
		consts.InitJobScriptFileName,
		ConfigFormatText,
		func() ([]byte, error) {
			text, err := initJob.script()
			if err != nil {
				return nil, err
			}
			return []byte(strings.Join(text, "\n")), nil
		},
	)

	return initJob
}

func NewInitJobForYtsaurus(
	labeller *labeller.Labeller,
	ytsaurus *apiproxy.Ytsaurus,
	name, configFileName string,
	generator ConfigGeneratorFunc,
	instanceSpec *ytv1.InstanceSpec,
) *InitJob {
	return NewInitJob(
		labeller,
		ytsaurus,
		name,
		configFileName,
		generator,
		ytsaurus.GetCommonSpec(),
		ytsaurus.GetCommonPodSpec(),
		instanceSpec,
	)
}

func (j *InitJob) Name() string {
	return j.initJob.Name()
}

func (j *InitJob) Restart() {
	// NOTE: Remove condition to trigger fresh start at next Sync.
	j.owner.RemoveStatusCondition(j.statusCondition)
}

func (j *InitJob) IsStarted() bool {
	condition := j.owner.GetStatusCondition(j.statusCondition)
	return condition != nil && condition.Reason == j.reason
}

func (j *InitJob) IsCompleted() bool {
	condition := j.owner.GetStatusCondition(j.statusCondition)
	return condition != nil && condition.Reason == j.reason && condition.Status == metav1.ConditionTrue
}

func (j *InitJob) SetInitScript(script string) {
	j.script = func() ([]string, error) {
		return []string{script}, nil
	}
}

func (j *InitJob) RunScript(
	ctx context.Context,
	dry bool,
	reason string,
	script TextGeneratorFunc,
	complete func(status *ComponentStatus),
) (ComponentStatus, error) {
	j.reason = reason
	j.script = script
	status, err := j.Sync(ctx, dry)
	if err == nil && status.IsReady() && complete != nil {
		complete(&status)
	}
	return status, err
}

func (j *InitJob) RunUpdateScript(
	ctx context.Context,
	dry bool,
	ytsaurus *apiproxy.Ytsaurus,
	updateState ytv1.UpdateState,
	script TextGeneratorFunc,
	complete func(),
) (ComponentStatus, error) {
	updateCondition := ytsaurus.GetUpdateStateCompleteCondition(updateState)
	if ytsaurus.GetUpdateStatusCondition(updateCondition) == nil {
		if dry {
			return ComponentStatusWaitingFor("job %s start", j.Name()), nil
		}
		j.Restart()
		ytsaurus.SetUpdateStatusCondition(ctx, metav1.Condition{
			Type:    updateCondition,
			Status:  metav1.ConditionFalse,
			Reason:  "JobStarting",
			Message: fmt.Sprintf("Job %v for %v is starting", j.Name(), updateState),
		})
	}
	return j.RunScript(ctx, dry, string(updateState), script, func(status *ComponentStatus) {
		if dry {
			*status = ComponentStatusWaitingFor("update condition %v", updateCondition)
			return
		}

		if complete != nil {
			complete()
		}

		*status = ComponentStatusReadyAfter("Job %v for %v is complete in %v", j.Name(), updateState, j.initJob.Duration())
		ytsaurus.LogUpdate(ctx, status.Message)
		ytsaurus.SetUpdateStatusCondition(ctx, metav1.Condition{
			Type:    updateCondition,
			Status:  metav1.ConditionTrue,
			Reason:  "JobComplete",
			Message: status.Message,
		})
	})
}

func (j *InitJob) Build() *batchv1.Job {
	if j.builtJob != nil {
		return j.builtJob
	}
	job := j.initJob.Build()
	job.Spec = batchv1.JobSpec{
		// NOTE: Job fails and retries after reaching backoff limit.
		BackoffLimit:            ptr.To(int32(3)),
		ActiveDeadlineSeconds:   ptr.To(int64(60 * 60)),
		TTLSecondsAfterFinished: ptr.To(int32(60 * 60)),
		Template: corev1.PodTemplateSpec{
			ObjectMeta: j.labeller.GetInitJobObjectMeta(),
			Spec: corev1.PodSpec{
				ImagePullSecrets: j.commonSpec.ImagePullSecrets,
				Containers: []corev1.Container{
					{
						Image: ptr.Deref(j.instanceSpec.Image, j.commonSpec.CoreImage),
						Name:  "ytsaurus-init",
						Command: []string{
							"/bin/bash",
							"-eux",
							path.Join(consts.ConfigMountPoint, consts.InitJobScriptFileName),
						},
						Env:     getDefaultEnv(),
						EnvFrom: j.envFrom,
						VolumeMounts: []corev1.VolumeMount{{
							Name:      consts.InitScriptVolumeName,
							MountPath: consts.ConfigMountPoint,
							ReadOnly:  true,
						}},
						TerminationMessagePolicy: corev1.TerminationMessageFallbackToLogsOnError,
					},
				},
				Volumes: []corev1.Volume{{
					Name: consts.InitScriptVolumeName,
					VolumeSource: corev1.VolumeSource{
						ConfigMap: &corev1.ConfigMapVolumeSource{
							LocalObjectReference: corev1.LocalObjectReference{
								Name: j.configs.GetConfigMapName(),
							},
							DefaultMode: ptr.To(int32(0o500)),
						},
					},
				}},
				RestartPolicy:     corev1.RestartPolicyOnFailure,
				Tolerations:       getTolerationsWithDefault(j.instanceSpec.Tolerations, j.commonPodSpec.Tolerations),
				NodeSelector:      getNodeSelectorWithDefault(j.instanceSpec.NodeSelector, j.commonPodSpec.NodeSelector),
				DNSConfig:         ptrDefault(j.instanceSpec.DNSConfig, j.commonPodSpec.DNSConfig),
				SetHostnameAsFQDN: ptr.To(ptr.Deref(j.instanceSpec.SetHostnameAsFQDN, ptr.Deref(j.commonPodSpec.SetHostnameAsFQDN, true))),
			},
		},
	}

	podSpec := &job.Spec.Template.Spec

	if ptr.Deref(j.instanceSpec.HostNetwork, ptr.Deref(j.commonPodSpec.HostNetwork, false)) {
		podSpec.HostNetwork = true
		// https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
		podSpec.DNSPolicy = corev1.DNSClusterFirstWithHostNet
	}
	podSpec.DNSPolicy = ptr.Deref(j.instanceSpec.DNSPolicy, ptr.Deref(j.commonPodSpec.DNSPolicy, podSpec.DNSPolicy))

	j.caRootBundle.AddVolume(&job.Spec.Template.Spec)
	j.caRootBundle.AddVolumeMount(&job.Spec.Template.Spec.Containers[0])
	j.caRootBundle.AddContainerEnv(&job.Spec.Template.Spec.Containers[0])

	j.caBundle.AddVolume(&job.Spec.Template.Spec)
	j.caBundle.AddVolumeMount(&job.Spec.Template.Spec.Containers[0])

	j.busClientSecret.AddVolume(&job.Spec.Template.Spec)
	j.busClientSecret.AddVolumeMount(&job.Spec.Template.Spec.Containers[0])

	j.builtJob = job
	return job
}

func (j *InitJob) Fetch(ctx context.Context) error {
	return resources.Fetch(ctx, j.initJob, j.configs)
}

func (j *InitJob) Exists() bool {
	return resources.Exists(j.initJob, j.configs)
}

func (j *InitJob) start(ctx context.Context, dry bool, isRestarted bool) (ComponentStatus, error) {
	if dry {
		return ComponentStatusWaitingFor("job %s start", j.Name()), nil
	}

	if j.initJob.Exists() {
		// NOTE: Delete previous pods in foreground to avoid concurrent invocations.
		err := j.initJob.DeleteForeground(ctx)
		return ComponentStatusWaitingFor("job %v delete", j.Name()), err
	}

	if _, err := j.configs.Build(); err != nil {
		return ComponentStatusWaitingFor("job %v configmap %v", j.Name(), j.configs.GetConfigMapName()), err
	}
	// NOTE: Track job reason in configmap annotation but not recreate to allow manual fixes for failing job.
	if isRestarted || !j.configs.Exists() || j.configs.getAnnotation(consts.InitJobReasonAnnotationName) != j.reason {
		j.configs.setAnnotation(consts.InitJobReasonAnnotationName, j.reason)
		if err := j.configs.Sync(ctx); err != nil {
			return ComponentStatusWaitingFor("job %v configmap %v", j.Name(), j.configs.GetConfigMapName()), err
		}
	}

	_ = j.Build()
	if err := j.initJob.Sync(ctx); err != nil {
		return ComponentStatusWaitingFor("job %s start", j.Name()), err
	}

	j.owner.SetStatusCondition(metav1.Condition{
		Type:    j.statusCondition,
		Status:  metav1.ConditionFalse,
		Reason:  j.reason,
		Message: fmt.Sprintf("Job %s started", j.Name()),
	})
	return ComponentStatusWaitingFor("job %s completion", j.Name()), nil
}

func (j *InitJob) Sync(ctx context.Context, dry bool) (ComponentStatus, error) {
	condition := j.owner.GetStatusCondition(j.statusCondition)
	isCompleted := condition != nil && condition.Reason == j.reason && condition.Status == metav1.ConditionTrue
	if isCompleted {
		return ComponentStatusReadyAfter("Job %v completed in %v", j.Name(), j.initJob.Duration()), nil
	}

	isStarted := condition != nil && condition.Reason == j.reason
	if !j.Exists() || !isStarted || j.initJob.IsFailed() {
		isRestarted := condition == nil
		return j.start(ctx, dry, isRestarted)
	}

	if !j.initJob.IsComplete() {
		jobStatus := j.initJob.Status()
		status := ComponentStatusWaitingFor("job %v completion, active: %v, failed: %v", j.Name(), jobStatus.Active, jobStatus.Failed)
		if !dry {
			j.owner.SetStatusCondition(metav1.Condition{
				Type:    j.statusCondition,
				Status:  metav1.ConditionFalse,
				Reason:  j.reason,
				Message: status.Message,
			})
		}
		return status, nil
	}

	if !dry {
		j.owner.SetStatusCondition(metav1.Condition{
			Type:    j.statusCondition,
			Status:  metav1.ConditionTrue,
			Reason:  j.reason,
			Message: fmt.Sprintf("Job %v completed in %v", j.Name(), j.initJob.Duration()),
		})
	}

	return ComponentStatusWaitingFor("condition %s", j.statusCondition), nil
}
