package components

import (
	"context"
	"fmt"
	"path"
	"slices"
	"strings"

	"k8s.io/utils/ptr"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	ytv1 "github.com/ytsaurus/ytsaurus-k8s-operator/api/v1"

	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/apiproxy"
	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/consts"
	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/labeller"
	"github.com/ytsaurus/ytsaurus-k8s-operator/pkg/resources"
)

const initJobPrologue = `#!/bin/bash
# YTsaurus init job script generated by ytsaurus-k8s-operator

set -eux -o pipefail
`

func initJobWithNativeDriverPrologue() string {
	commands := []string{
		initJobPrologue,
		fmt.Sprintf("export YT_DRIVER_CONFIG_PATH=%s", path.Join(consts.ConfigMountPoint, consts.ClientConfigFileName)),
	}
	return strings.Join(commands, "\n")
}

type InitJob struct {
	component

	commonSpec    *ytv1.CommonSpec
	commonPodSpec *ytv1.PodSpec
	instanceSpec  *ytv1.InstanceSpec

	initJob *resources.Job
	configs *ConfigMapBuilder
	envFrom []corev1.EnvFromSource

	caRootBundle    *resources.CABundle
	caBundle        *resources.CABundle
	busClientSecret *resources.TLSSecret

	statusCondition string // Condition for tracking job state.
	reason          string // Changing reason triggers fresh start.
	scriptFileName  string // Name of the script to execute.
	logFilePath     string

	builtJob *batchv1.Job
}

func NewInitJob(
	labeller *labeller.Labeller,
	apiProxy apiproxy.APIProxy,
	name string,
	commonSpec *ytv1.CommonSpec,
	commonPodSpec *ytv1.PodSpec,
	instanceSpec *ytv1.InstanceSpec,
	generators ...ConfigGenerator,
) *InitJob {
	var busClientSecret *resources.TLSSecret

	if transportSpec := commonSpec.NativeTransport; transportSpec != nil {
		if transportSpec.TLSClientSecret != nil {
			busClientSecret = resources.NewTLSSecret(
				transportSpec.TLSClientSecret.Name,
				consts.BusClientSecretVolumeName,
				consts.BusClientSecretMountPoint)
		}
	}

	initJob := &InitJob{
		component: component{
			labeller: labeller,
			owner:    apiProxy,
		},
		commonSpec:      commonSpec,
		commonPodSpec:   commonPodSpec,
		instanceSpec:    instanceSpec,
		statusCondition: labeller.GetInitJobCompletedCondition(name),
		reason:          consts.InitJobDefaultReason,
		initJob: resources.NewJob(
			labeller.GetInitJobName(name),
			labeller,
			apiProxy,
		),
		caRootBundle:    resources.NewCARootBundle(commonSpec.CARootBundle),
		caBundle:        resources.NewCABundle(commonSpec.CABundle),
		busClientSecret: busClientSecret,
		configs: NewConfigMapBuilder(
			labeller,
			apiProxy,
			labeller.GetInitJobConfigMapName(name),
			nil,
			generators...,
		),
		scriptFileName: consts.InitJobScriptName,
	}

	if location := ytv1.FindFirstLocation(instanceSpec.Locations, ytv1.LocationTypeInitJobLogs); location != nil {
		initJob.logFilePath = path.Join(location.Path, initJob.Name()+".log")
	}

	return initJob
}

func NewInitJobForYtsaurus(
	labeller *labeller.Labeller,
	ytsaurus *apiproxy.Ytsaurus,
	name string,
	instanceSpec *ytv1.InstanceSpec,
	generators ...ConfigGenerator,
) *InitJob {
	return NewInitJob(
		labeller,
		ytsaurus,
		name,
		ytsaurus.GetCommonSpec(),
		ytsaurus.GetCommonPodSpec(),
		instanceSpec,
		generators...,
	)
}

func (j *InitJob) AddScript(fileName string, generator TextGeneratorFunc) {
	j.configs.AddGenerator(fileName, ConfigFormatText, func() ([]byte, error) {
		text, err := generator()
		if err != nil {
			return nil, err
		}
		return []byte(strings.Join(text, "\n")), nil
	})
}

// TODO: Migrate to AddScript.
func (j *InitJob) AddInitJobScript(generator func() string) {
	j.configs.AddGenerator(consts.InitJobScriptName, ConfigFormatText, func() ([]byte, error) {
		return []byte(generator()), nil
	})
}

func (j *InitJob) Name() string {
	return j.initJob.Name()
}

func (j *InitJob) Restart() {
	// NOTE: Remove condition to trigger fresh start at next Sync.
	j.owner.RemoveStatusCondition(j.statusCondition)
}

// IsCompleted returns true if job spec and config exist and job status condition is "True".
// NOTE: Not checking job success to allow manual setting condition for failing jobs.
// NOTE: Removing either job spec, config or condition triggers job restart.
func (j *InitJob) IsCompleted() bool {
	return j.Exists() && j.owner.IsStatusConditionTrue(j.statusCondition)
}

func (j *InitJob) RunScript(
	ctx context.Context,
	dry bool,
	reason string,
	scriptFileName string,
	complete func(status *ComponentStatus),
) (ComponentStatus, error) {
	if !slices.ContainsFunc(j.configs.generators, func(g ConfigGenerator) bool { return g.FileName == scriptFileName }) {
		err := fmt.Errorf("generator not found: %v", scriptFileName)
		return ComponentStatusBlocked("%v", err), err
	}
	j.reason = reason
	j.scriptFileName = scriptFileName
	j.builtJob = nil
	status, err := j.Sync(ctx, dry)
	if err == nil && status.IsReady() && complete != nil {
		complete(&status)
	}
	return status, err
}

func (j *InitJob) RunUpdateScript(
	ctx context.Context,
	dry bool,
	ytsaurus *apiproxy.Ytsaurus,
	updateState ytv1.UpdateState,
	scriptFileName string,
	complete func(),
) (ComponentStatus, error) {
	updateCondition := ytsaurus.GetUpdateStateCompleteCondition(updateState)
	if ytsaurus.GetUpdateStatusCondition(updateCondition) == nil {
		if dry {
			return ComponentStatusWaitingFor("job %s start for update %v", j.Name(), updateState), nil
		}
		j.Restart()
		ytsaurus.SetUpdateStatusCondition(ctx, metav1.Condition{
			Type:    updateCondition,
			Status:  metav1.ConditionFalse,
			Reason:  "JobStarting",
			Message: fmt.Sprintf("Job %v is starting", j.Name()),
		})
	}
	return j.RunScript(ctx, dry, string(updateState), scriptFileName, func(status *ComponentStatus) {
		if dry {
			// NOTE: Return non-ready status to trigger component sync and set update condition.
			*status = ComponentStatusWaitingFor("update condition %v after completing job", updateCondition)
			return
		}

		if complete != nil {
			complete()
		}

		*status = ComponentStatusReadyAfter("Job %v for update %v is complete in %v", j.Name(), updateState, j.initJob.Duration())
		ytsaurus.LogUpdate(ctx, status.Message)
		ytsaurus.SetUpdateStatusCondition(ctx, metav1.Condition{
			Type:    updateCondition,
			Status:  metav1.ConditionTrue,
			Reason:  "JobComplete",
			Message: status.Message,
		})
	})
}

func (j *InitJob) Build() *batchv1.Job {
	if j.builtJob != nil {
		return j.builtJob
	}
	scriptFilePath := path.Join(consts.ConfigMountPoint, j.scriptFileName)
	job := j.initJob.Build()
	job.Spec = batchv1.JobSpec{
		// NOTE: Jobs are not deleted automatically. Delete triggers job restart.
		// NOTE: Job fails and retries after reaching backoff limit.
		BackoffLimit:          ptr.To(int32(3)),
		ActiveDeadlineSeconds: ptr.To(int64(60 * 60)),
		Template: corev1.PodTemplateSpec{
			ObjectMeta: j.labeller.GetInitJobObjectMeta(),
			Spec: corev1.PodSpec{
				ImagePullSecrets: j.commonSpec.ImagePullSecrets,
				Containers: []corev1.Container{
					{
						Image: ptr.Deref(j.instanceSpec.Image, j.commonSpec.CoreImage),
						Name:  "ytsaurus-init",
						Command: []string{
							"/bin/bash",
							"-eux",
							scriptFilePath,
						},
						Env:     getDefaultEnv(),
						EnvFrom: j.envFrom,
						VolumeMounts: []corev1.VolumeMount{{
							Name:      consts.InitScriptVolumeName,
							MountPath: consts.ConfigMountPoint,
							ReadOnly:  true,
						}},
						TerminationMessagePolicy: corev1.TerminationMessageFallbackToLogsOnError,
					},
				},
				Volumes: []corev1.Volume{{
					Name: consts.InitScriptVolumeName,
					VolumeSource: corev1.VolumeSource{
						ConfigMap: &corev1.ConfigMapVolumeSource{
							LocalObjectReference: corev1.LocalObjectReference{
								Name: j.configs.GetConfigMapName(),
							},
							DefaultMode: ptr.To(int32(0o500)),
						},
					},
				}},
				RestartPolicy:     corev1.RestartPolicyOnFailure,
				Tolerations:       getTolerationsWithDefault(j.instanceSpec.Tolerations, j.commonPodSpec.Tolerations),
				NodeSelector:      getNodeSelectorWithDefault(j.instanceSpec.NodeSelector, j.commonPodSpec.NodeSelector),
				DNSConfig:         ptrDefault(j.instanceSpec.DNSConfig, j.commonPodSpec.DNSConfig),
				SetHostnameAsFQDN: ptr.To(ptr.Deref(j.instanceSpec.SetHostnameAsFQDN, ptr.Deref(j.commonPodSpec.SetHostnameAsFQDN, true))),
			},
		},
	}

	metav1.SetMetaDataAnnotation(&job.ObjectMeta, consts.InitJobReasonAnnotationName, j.reason)
	metav1.SetMetaDataAnnotation(&job.Spec.Template.ObjectMeta, consts.InitJobReasonAnnotationName, j.reason)

	podSpec := &job.Spec.Template.Spec

	if ptr.Deref(j.instanceSpec.HostNetwork, ptr.Deref(j.commonPodSpec.HostNetwork, false)) {
		podSpec.HostNetwork = true
		// https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
		podSpec.DNSPolicy = corev1.DNSClusterFirstWithHostNet
	}
	podSpec.DNSPolicy = ptr.Deref(j.instanceSpec.DNSPolicy, ptr.Deref(j.commonPodSpec.DNSPolicy, podSpec.DNSPolicy))

	j.caRootBundle.AddVolume(&job.Spec.Template.Spec)
	j.caRootBundle.AddVolumeMount(&job.Spec.Template.Spec.Containers[0])
	j.caRootBundle.AddContainerEnv(&job.Spec.Template.Spec.Containers[0])

	j.caBundle.AddVolume(&job.Spec.Template.Spec)
	j.caBundle.AddVolumeMount(&job.Spec.Template.Spec.Containers[0])

	j.busClientSecret.AddVolume(&job.Spec.Template.Spec)
	j.busClientSecret.AddVolumeMount(&job.Spec.Template.Spec.Containers[0])

	if j.logFilePath != "" {
		job.Spec.Template.Spec.Containers[0].Command = []string{
			"/bin/bash",
			"-euxc",
			"exec &> >(tee -a " + j.logFilePath + "); . " + scriptFilePath,
		}
		logMounts, err := resolveLocationMounts(j.instanceSpec, ytv1.LocationTypeInitJobLogs)
		if err == nil && len(logMounts) != 0 {
			job.Spec.Template.Spec.Containers[0].VolumeMounts = append(job.Spec.Template.Spec.Containers[0].VolumeMounts, logMounts...)
			ownerName := j.labeller.GetComponentShortName()
			if j.labeller.ComponentType == consts.YtsaurusClientType {
				ownerName = j.labeller.ForComponent(consts.MasterType, "").GetComponentShortName()
			}
			pvcSuffix := fmt.Sprintf("-%s-0", ownerName)
			job.Spec.Template.Spec.Volumes = append(job.Spec.Template.Spec.Volumes, resolveVolumeMounts(j.instanceSpec, logMounts, pvcSuffix)...)
		}
	}

	j.builtJob = job
	return job
}

func (j *InitJob) Fetch(ctx context.Context) error {
	return resources.Fetch(ctx, j.initJob, j.configs)
}

func (j *InitJob) Exists() bool {
	return resources.Exists(j.initJob, j.configs)
}

func (j *InitJob) start(ctx context.Context, dry, isStarted, isRestarted bool) (ComponentStatus, error) {
	if dry {
		return ComponentStatusWaitingFor("job %s start for reason %v", j.Name(), j.reason), nil
	}

	if j.initJob.Exists() {
		// NOTE: Delete previous pods in foreground to avoid concurrent invocations.
		err := j.initJob.DeleteForeground(ctx)
		return ComponentStatusWaitingFor("job %v delete for reason %v", j.Name(), j.reason), err
	}

	if isRestarted && j.configs.Exists() {
		err := j.configs.configMap.DeleteBackground(ctx)
		return ComponentStatusWaitingFor("job %v configmap %v delete", j.Name(), j.configs.GetConfigMapName()), err
	}

	if !isStarted {
		// NOTE: Set condition reason to checkpoint fresh (re)start.
		j.owner.SetStatusCondition(metav1.Condition{
			Type:    j.statusCondition,
			Status:  metav1.ConditionFalse,
			Reason:  j.reason,
			Message: fmt.Sprintf("Job %s starting", j.Name()),
		})
		return ComponentStatusWaitingFor("job %v starting for reason %v", j.Name(), j.reason), nil
	}

	if _, err := j.configs.Build(); err != nil {
		return ComponentStatusWaitingFor("job %v configmap %v for reason %v", j.Name(), j.configs.GetConfigMapName(), j.reason), err
	}

	// NOTE: Track job reason in configmap annotation but not recreate to allow manual fixes for failing job.
	if !j.configs.Exists() || j.configs.getAnnotation(consts.InitJobReasonAnnotationName) != j.reason {
		j.configs.setAnnotation(consts.InitJobReasonAnnotationName, j.reason)
		if err := j.configs.Sync(ctx); err != nil {
			return ComponentStatusWaitingFor("job %v configmap %v for reason %v", j.Name(), j.configs.GetConfigMapName(), j.reason), err
		}
	}

	_ = j.Build()
	if err := j.initJob.Sync(ctx); err != nil {
		return ComponentStatusWaitingFor("job %s start for reason %v", j.Name(), j.reason), err
	}

	message := fmt.Sprintf("Job %s started", j.Name())
	j.owner.RecordNormal(j.reason, message)
	j.owner.SetStatusCondition(metav1.Condition{
		Type:    j.statusCondition,
		Status:  metav1.ConditionFalse,
		Reason:  j.reason,
		Message: message,
	})
	return ComponentStatusWaitingFor("job %s condition %v for reason %v completion", j.Name(), j.statusCondition, j.reason), nil
}

func (j *InitJob) Sync(ctx context.Context, dry bool) (ComponentStatus, error) {
	condition := j.owner.GetStatusCondition(j.statusCondition)
	isCompleted := condition != nil && condition.Reason == j.reason && condition.Status == metav1.ConditionTrue
	isExists := j.Exists()
	if isExists && isCompleted {
		// NOTE: Not checking init job status to allow manual setting condition to "True".
		return ComponentStatusReadyAfter("Job %v condition %v for reason %v completed in %v", j.Name(), j.statusCondition, j.reason, j.initJob.Duration()), nil
	}

	isStarted := condition != nil && condition.Reason == j.reason
	if !isStarted || !isExists || j.initJob.IsFailed() {
		isRestarted := condition == nil
		return j.start(ctx, dry, isStarted, isRestarted)
	}

	if !j.initJob.IsComplete() {
		jobStatus := j.initJob.Status()
		status := ComponentStatusWaitingFor("job %v condition %v for reason %v completion, active: %v, failed: %v",
			j.Name(),
			j.statusCondition,
			j.reason,
			jobStatus.Active,
			jobStatus.Failed,
		)
		if !dry {
			j.owner.SetStatusCondition(metav1.Condition{
				Type:    j.statusCondition,
				Status:  metav1.ConditionFalse,
				Reason:  j.reason,
				Message: status.Message,
			})
		}
		return status, nil
	}

	if !dry {
		message := fmt.Sprintf("Job %v completed in %v", j.Name(), j.initJob.Duration())
		j.owner.RecordNormal(j.reason, message)
		j.owner.SetStatusCondition(metav1.Condition{
			Type:    j.statusCondition,
			Status:  metav1.ConditionTrue,
			Reason:  j.reason,
			Message: message,
		})
	}

	return ComponentStatusWaitingFor("job %v condition %s for reason %v", j.Name(), j.statusCondition, j.reason), nil
}
