package consts

const ConditionHasPossibility = "HasPossibility"
const ConditionNoPossibility = "NoPossibility"
const ConditionSafeModeEnabled = "SafeModeEnabled"
const ConditionTabletCellsSaved = "TabletCellsSaved"
const ConditionTabletCellsRemovingStarted = "TabletCellsRemovingStarted"
const ConditionTabletCellsRemoved = "TabletCellsRemoved"
const ConditionSnapshotsBuildingStarted = "SnapshotsBuildingStarted"
const ConditionSnapshotsMonitoringInfoSaved = "SnapshotsMonitoringInfoSaved"
const ConditionSnaphotsSaved = "SnaphotsSaved"
const ConditionTabletCellsRecovered = "TabletCellsRecovered"
const ConditionOpArchiveUpdated = "OpArchiveUpdated"
const ConditionOpArchivePreparedForUpdating = "OpArchivePreparedForUpdating"
const ConditionQTStateUpdated = "QTStateUpdated"
const ConditionQTStatePreparedForUpdating = "QTStatePreparedForUpdating"
const ConditionYqlaUpdated = "YqlaUpdated"
const ConditionYqlaPreparedForUpdating = "YqlaPreparedForUpdating"
const ConditionMasterExitReadOnlyPrepared = "MasterExitReadOnlyPrepared"
const ConditionMasterExitedReadOnly = "MasterExitedReadOnly"
const ConditionRealChunkLocationsEnablePrepared = "RealChunkLocationsEnablePrepared"
const ConditionRealChunkLocationsEnabled = "RealChunkLocationsEnabled"
const ConditionSafeModeDisabled = "SafeModeDisabled"
