package consts

const ConditionHasPossibility = "HasPossibility"
const ConditionNoPossibility = "NoPossibility"
const ConditionSafeModeEnabled = "SafeModeEnabled"
const ConditionTabletCellsSaved = "TabletCellsSaved"
const ConditionTabletCellsRemovingStarted = "TabletCellsRemovingStarted"
const ConditionTabletCellsRemoved = "TabletCellsRemoved"
const ConditionSnapshotsBuildingStarted = "SnapshotsBuildingStarted"
const ConditionSnapshotsMonitoringInfoSaved = "SnapshotsMonitoringInfoSaved"
const ConditionSnaphotsSaved = "SnaphotsSaved"
const ConditionTabletCellsRecovered = "TabletCellsRecovered"
const ConditionOpArchiveUpdated = "OpArchiveUpdated"
const ConditionOpArchivePreparedForUpdating = "OpArchivePreparedForUpdating"
const ConditionNotNecessaryToUpdateOpArchive = "NotNecessaryToUpdateOpArchive"
const ConditionQTStateUpdated = "QTStateUpdated"
const ConditionQTStatePreparedForUpdating = "QTStatePreparedForUpdating"
const ConditionSafeModeDisabled = "SafeModeDisabled"
