apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ytop-chart.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "ytop-chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}