apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ytop-chart.fullname" . }}-controller-manager
  labels:
  {{- include "ytop-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}