name: Linters

on:
  push:
    branches:
      - main

  pull_request: {}
  workflow_dispatch: {}

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: checkout sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      # https://github.com/actions/setup-go
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Run code linters
        shell: bash
        run: |
          make lint

      - name: Check generated files
        shell: bash
        run: |
          make lint-generated
