name: Build and test

on:
  push:
    branches:
      - main

jobs:
  check-unit:
    name: Run unit tests
    uses: ./.github/workflows/subflow_run_unit_tests.yaml

  check-e2e:
    name: Run e2e tests
    needs:
      - check-unit
    uses: ./.github/workflows/subflow_run_e2e_tests.yaml

  check-compat:
    name: Run compat tests
    needs:
      - check-e2e
    uses: ./.github/workflows/subflow_run_compat_tests.yaml
