name: Run extra e2e tests (part 2)

on:
  pull_request:

jobs:
  check:
    name: Run extra e2e tests (part 2)
    uses: ./.github/workflows/subflow_run_e2e_tests.yaml
    with:
      e2e_filter: "!basic && !selector && !remote"
