name: "Unit Tests"

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run unit tests
        shell: bash
        run: |
          make test
