name: "Unit Tests"

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            runs-on: ubuntu-latest
          - name: macos
            runs-on: macos-latest

    name: Run checks on ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run unit tests
        shell: bash
        run: |
          make test
